# Generated by Django 5.0.3 on 2024-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='descripion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficult',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='gpx',
            field=models.FileField(upload_to='main/routes_files/gpx/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='lenght',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='main_image',
            field=models.ImageField(upload_to='main/routes_files/images/additional/'),
        ),
    ]
