# Generated by Django 5.0.3 on 2024-06-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_placemark_route_placemarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='main/routes_files/images'),
        ),
        migrations.AlterField(
            model_name='route',
            name='additional_images',
            field=models.ManyToManyField(related_name='additional_images', to='main.image'),
        ),
        migrations.AlterField(
            model_name='route',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_image', to='main.image'),
        ),
    ]
