# Generated by Django 5.0.3 on 2024-06-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='route_images/general/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descripion', models.CharField(max_length=300)),
                ('difficult', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='route_images/additional/')),
                ('gpx', models.FileField(upload_to='route_gpx/')),
                ('additional_images', models.ManyToManyField(to='users.image')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.type')),
            ],
        ),
    ]
