# Generated by Django 5.0.3 on 2024-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_image_type_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default='Изображение', max_length=30),
        ),
    ]
